[tool.pytest.ini_options]
pythonpath = ["scripts/hooks"]

[tool.coverage.run]
omit = [
    "*/test_*.py", # Exclude files matching 'test_*.py' pattern anywhere
    "*/conftest.py", # Exclude files matching 'test_*.py' pattern anywhere
]